feat(client): disable hold r to restart while in lobby
V-rtualized/balatro-multiplayer pull request #51
Opened 2024-05-27 10:43 UTC by CUexter

2024-05-27 20:41 UTC, V-rtualized commented on Multiplayer/Misc/disable-restart.lua
> +end
We probably don't want to use the entire source function's code, as it could change in the future. Something like this does the same thing right?
```suggestion
local key_hold_update_ref = Controller.key_hold_update
function Controller:key_hold_update(key, dt)
	if not G.LOBBY.code then
		key_hold_update_ref(self, key, dt)
	end
end
```

2024-05-27 20:54 UTC, TGMM requested changes

2024-05-27 20:54 UTC, TGMM commented on Multiplayer/Core.lua
> +	require("Misc.disable-restart")
Small nitpick, but we should stick to the naming convention if possible. This should be `Misc.Disable_Restart` instead.

2024-05-27 21:45 UTC, V-rtualized approved these changes
Once TGMM's request is fixed, this looks good :)

2024-05-28 11:00 UTC, CUexter commented
After the server is rewritten i will implement a vote to restart system

2024-05-28 11:01 UTC, merged